[config]
# ...
[config.wallpaper]
command = "swww"
arguments = ["img", "--transition-type", "center"]
set = true

[templates.hyprland]
input_path = '~/.config/hypr/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'
[templates.alacritty]
input_path = '~/.config/matugen/alacritty.toml'
output_path = '~/.config/alacritty/colors.toml'
[templates.gtk3]
input_path = '~/.config/matugen/gtk-colors.css'
output_path = '~/.config/gtk-3.0/colors.css'
post_hook = 'gsettings set org.gnome.desktop.interface gtk-theme ""; gsettings set org.gnome.desktop.interface gtk-theme adw-gtk3-{{mode}}'

[templates.gtk4]
input_path = '~/.config/matugen/gtk-colors.css'
output_path = '~/.config/gtk-4.0/colors.css'


[templates.qt6ct]
input_path = '~/.config/matugen/qtct-colors.conf'
output_path = '~/.config/qt6ct/colors/matugen.conf'

[templates.qt5ct]
input_path = '~/.config/matugen/qtct-colors.conf'
output_path = '~/.config/qt5ct/colors/matugen.conf'
[templates.pywalfox]
input_path = '~/.config/matugen/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'
[templates.starship]
input_path = '~/.config/matugen/starship-colors.toml'
output_path = '~/.config/starship.toml'
[templates.rofi]
input_path = '~/.config/matugen/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'
[templates.waybar]
input_path = '~/.config/matugen/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'
[templates.wlogout]
input_path = '~/.config/matugen/colors.css'
output_path = '~/.config/wlogout/colors.css'
