format = '''
$directory$git_branch$rust$python
$character'''

palette = 'colors'

[palettes.colors]
mustard = '#af8700' # example
color1 = '#dfc1a3'
color2 = '#3f2d17'
color3 = '#d1c4b9'
color4 = '#221f1d'
color5 = '#3f2d17'
color6 = '#151311'
color7 = '#151311'
color8 = '#dfc1a3'
color9 = '#b9c8d9'

# Prompt symbols 
[character]
success_symbol = "[ÔÑ∏](color1)"
error_symbol = "[ÔÑ∏](color1)"
vicmd_symbol = "[ÔÑ∏](color1)"

[directory]
format = "[ÓÇ∂](fg:color1 bg:color4)[ÔÅª ](bg:color1 fg:color2)[ÓÇ¥ ](fg:color1 bg:color4)[$path ](fg:color3 bg:color4)[ÓÇ¥ ](fg:color4)"

[directory.substitutions]
"Documents" = "Û∞àô "
"Downloads" = "ÔÄô "
"Music" = "ÔÄÅ "
"Pictures" = "ÔÄæ "

[git_branch]
format = "[ÓÇ∂](fg:color8 bg:color4)[Ôáì ](bg:color8 fg:color5)[ÓÇ¥](fg:color8 bg:color4)[(bg:color8 fg:color5) $branch](fg:color3 bg:color4)[ÓÇ¥](fg:color4) "

[time]
format = "[ÓÇ∂](fg:color8 bg:color4)[Ôê∫ ](bg:color8 fg:color5)[ÓÇ¥](fg:color8 bg:color4)[(bg:color8 fg:color5) $time](fg:color3 bg:color4)[ÓÇ¥](fg:color4) "
disabled = false
time_format = "%R" # Hour:Minute Format

[python]
format = "[ÓÇ∂](fg:color8 bg:color4)[${symbol}${version}](bg:color8 fg:color5)[ÓÇ¥](fg:color8 bg:color4)[(bg:color8 fg:color5)( ${virtualenv})](fg:color3 bg:color4)[ÓÇ¥](fg:color4) "
symbol = 'üêç'
# pyenv_version_name = true
pyenv_prefix = 'venv'
