[colors.primary]
background = '#151311'
foreground = '#e8e1dd'
 
[colors.cursor]
text = '#e8e1dd'
cursor = '#d1c4b9' 
 
[colors.vi_mode_cursor]
text = '#151311'
cursor = '#dfc1a3' 
 
[colors.search.matches]
foreground = '#4e453d' 
background = '#b9c8d9' 
 
[colors.search.focused_match]
foreground = '#4e453d' 
background = '#dfc1a3' 
 
[colors.footer_bar]
foreground = '#4e453d' 
background = '#e8e1dd' 
 
[colors.hints.start]
foreground = '#4e453d' 
background = '#d4c4b5' 
 
[colors.hints.end]
foreground = '#4e453d' 
background = '#d4c4b5' 
 
[colors.selection]
text = '#151311'
background = '#dfc1a3'
 
 
[colors.normal]
black = '#181818' 
red = '#ffb4ab' 
green = '#dfc1a3' 
yellow = '#715a41' 
blue = '#dfc1a3' 
magenta = '#b9c8d9' 
cyan = '#d4c4b5' 
white = '#BAC2DE' 
 
 
[colors.bright]
black = '#585B70' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#A6ADC8' 
 
 
[colors.dim]
black = '#45475A' 
red = '#F38BA8' 
green = '#A6E3A1' 
yellow = '#F9E2AF' 
blue = '#89B4FA' 
magenta = '#F5C2E7' 
cyan = '#94E2D5' 
white = '#BAC2DE' 
